### ISSUE TITLE
¿Que URIs va a tener el contenido ELI?

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [opendata-euskadi/WebDocumentacionLinkedDataOpenDataEuskadi#1]
- URI NTI + URI ELI
- URI ELI solamente

**Comment by imanol-argueso** [comment]
Después de recibir la respuesta a nuestra consulta y hablarlo entre nosotros, hemos decidido que las **URIs de los recursos del ELI cumplirán íntegramente el patrón establecido por el grupo de trabajo ELI**:

/eli/{jurisdiction}/{type}/{year}/{month}/{day}/{naturalidentifier}/{version}/{pointintime}/{language}/{format}

Por tanto, serán una excepción en el patrón establecido para las URIs de los recursos de euskadi.eus que hemos definido en el proyecto Linked Data de Open Data Euskadi.

RESPUESTA A NUESTRA CONSULTA:

Buenos días Imanol,
La URI canónica del ELI debe formarse con arreglo al estándar definido por la Unión Europea. En el grupo de trabajo lo que hemos hecho es adaptar el estándar a las peculiaridades del sistema jurídico español, pero esa adaptación se ha hecho respetando el estándar y moviéndonos  siempre dentro del margen de elección que se deja a cada Estado. El modelo que proponeis de "combinación" del NTI y ELI no cumple con el modelo de ELI definido por el grupo, pero tampoco con el propio estánder definido por la UE.

Si no hemos entendido mal, puesto que vais a difundir la legislación desde el portal de normativa "legegunea", en vuestro caso la URL completa canónica de ELI sería la siguiente:

http://www.legegunea.euskadi.eus/eli/{jurisdiction}/{type}/{year}/{month}/{day}/{naturalidentifier}/{version}/{pointintime}/{language}/{format} 

Es decir, la URI comenzando con "/eli". 

Español: http://www.legegunea.euskadi.eus/es/eli/es-pv/dl/2018/02/06/00768/dof/spa/html
Euskera: http://www.legegunea.euskadi.eus/eu/eli/es-pv/dl/2018/02/06/00768/dof/eus/html 

Por cierto, detectamos que habría un error que os hemos marcado en rojo ya que sobra el primer elemento ("es" en el caso de la versión español y "eu" en la versión en euskera)

El modelo canónico de ELI es ese y se ha de respetar, así lo ha valorado también John Dann, con quien hablamos ayer sobre tu consulta.

Si en el proyecto Link Data que mencionáis tenéis previsto construir otras URLs conforme el modelo del NTI, podeis establecer un mecanismo de redireccionamiento entre estas y las de ELI pero las de ELI tendrían que seguir el modelo canónico establecido. 

Un saludo
José Manuel Ruiz

**Comment by mikel-egana-aranguren** [comment]
De acuerdo, añado la nueva info
