### ISSUE TITLE
Corregir URI ELI

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [opendata-euskadi/WebDocumentacionLinkedDataOpenDataEuskadi#5]
http://legegunea.euskadi.eus/eli/{jurisdiction}/{type}/{year}/{month}/{day}/{naturalidentifier}/{version}/{pointintime}/{language}/{format}

**Comment by SPANIAGU** [comment]
La URI tendrá este formato:
http://euskadi.eus/eli/{jurisdiction}/{type}/{year}/{month}/{day}/{naturalidentifier}/{version}/{pointintime}/{language}/{format}

Sólo si la URI es formato HTML y el agente es un navegador:
http://www.legegunea.euskadi.eus/eli/{jurisdiction}/{type}/{year}/{month}/{day}/{naturalidentifier}/{version}/{pointintime}/{language}/html

**Comment by mikel-egana-aranguren** [comment]
OK eskerrik asko
