### ISSUE TITLE
email de contacto

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [opendata-euskadi/WebDocumentacionLinkedDataOpenDataEuskadi#9]
Hace falta un email de contacto o formulario para poner en la web por si los desarrolladores externos tienen dudas

**Comment by imanol-argueso** [comment]
Hasta ahora suelen utilizar éste formulario que viene en la web: 
http://opendata.euskadi.eus/general/-/contacta-a-traves-de-internet-telefono-y-presencialmente/ 

http://opendata.euskadi.eus/orokorra/-/harremanetan-jartzeko-internet-telefonoa-eta-aurrez-aurre/
